### ISSUE TITLE
A new release is needed so that UIWebView is no longer used in the packages from pub.dev

### ISSUE THREAD

**Issue by MaskyS** [Clancey/simple_auth#130]
Please create a new release, currently, it is not possible to upload to the App Store when depending on the pub.dev as it hasn't been updated in a long time.

**Comment by MaskyS** [comment]
cc @Clancey

**Comment by uwemeier-sclable** [comment]
+1

The new fixes don't work, as now the build fails (also indicated in the README by [![Build status](https://build.appcenter.ms/v0.1/apps/788e968e-4f7d-4c90-a662-9877cee9d85a/branches/master/badge)](https://appcenter.ms) )

**Comment by uwemeier-sclable** [comment]
I opened a PR.  

Until then, this works:
In your `pubspec.yaml` file replace your `simple_auth_flutter`-dependency with

```yaml
  simple_auth_flutter:
    #TODO set back to ^2.0.7 and remove "git:..." when https://github.com/Clancey/simple_auth/pull/135 got merged
    git:
      url: git@github.com:uwemeier-sclable/simple_auth.git
      path: simple_auth_flutter
      ref: master
```

and add a dependency override for `simple_auth`
```yaml
#TODO remove simple_auth from dependency_overrides when https://github.com/Clancey/simple_auth/pull/135 got merged
dependency_overrides:
  simple_auth:
    git:
      url: git@github.com:uwemeier-sclable/simple_auth.git
      path: simple_auth
      ref: master
```

This PR (& workaround) is tested and uploads to Apples Appstore Connect work.
