### ISSUE TITLE
The plugin `simple_auth_flutter` uses a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by Veselchak-U** [Clancey/simple_auth#165]
Hello! 
I use the latest version of the library - 2.0.11. After upgrading to Flutter 2.5.0, during the execution of 'flutter pub get', I receive the following message:
```
The plugin `simple_auth_flutter` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
```

**Comment by evilmtv** [comment]
@Veselchak-U @rsree1210 
While not recommended, you may use the specific commit that has it fixed. I'm currently using the commit after that like so:
```
  simple_auth_flutter:
    git:
      url: https://github.com/Clancey/simple_auth.git
      ref: 52d9aea3be506ccf39aa8dc68fda97481743bd33
      path: simple_auth_flutter/
```
