### ISSUE TITLE
Instance of 'CancelledException'

### ISSUE THREAD

**Issue by breitembach** [Clancey/simple_auth#49]
```
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.7.0+1
  simple_auth_flutter: ^2.0.0
```
Error Log-in  with GoogleApi on Flutter Android
I'm redirected to the browser, I log into my account but I do not go back to the app anymore and I get an error
Instance of 'CancelledException'
and
Instance of 'Response<"String">'
